# Generated by Django 3.1.7 on 2022-10-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id_c', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_c', models.CharField(max_length=60)),
                ('imagen_c', models.ImageField(blank=True, null=True, upload_to='')),
                ('descripcion_c', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulomapp', models.CharField(max_length=50)),
                ('mensajeapp', models.CharField(max_length=150)),
                ('linkapp', models.CharField(max_length=150)),
                ('keyapp', models.CharField(max_length=200)),
                ('iconapp', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen_tag', models.ImageField(blank=True, null=True, upload_to='')),
                ('genero_tag', models.CharField(max_length=100)),
                ('idioma_tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Redsocial',
            fields=[
                ('id_rs', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_rs', models.CharField(max_length=30)),
                ('imagen_rs', models.ImageField(blank=True, null=True, upload_to='')),
                ('url_rs', models.CharField(max_length=150, null=True)),
                ('id_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.canal')),
            ],
        ),
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id_e', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_e', models.CharField(max_length=100)),
                ('imagen_e', models.ImageField(blank=True, null=True, upload_to='')),
                ('texto_e', models.CharField(max_length=1000, null=True)),
                ('url_e', models.CharField(max_length=200, null=True)),
                ('id_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.canal')),
                ('id_tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tag')),
            ],
        ),
        migrations.AddField(
            model_name='canal',
            name='id_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.tag'),
        ),
    ]
