# Generated by Django 3.1.7 on 2022-10-28 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20221027_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texto',
            old_name='id_c',
            new_name='id_e',
        ),
    ]
