# Generated by Django 3.1.7 on 2022-11-16 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20221028_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='texto',
            name='imagen_t',
        ),
    ]
